extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:react-hooks/recommended

parser: '@typescript-eslint/parser'
parserOptions:
    project: ./tsconfig.json
plugins:
    - '@typescript-eslint'

rules:
    '@typescript-eslint/no-confusing-void-expression': error
    '@typescript-eslint/no-unnecessary-condition': error
    '@typescript-eslint/prefer-nullish-coalescing': error
    '@typescript-eslint/prefer-optional-chain': error
    '@typescript-eslint/switch-exhaustiveness-check': error
    '@typescript-eslint/consistent-type-imports': error
    '@typescript-eslint/consistent-type-definitions': [error, type]
    '@typescript-eslint/explicit-module-boundary-types': off
