name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Installs the dependencies
        run: yarn
      - name: Runs the type checker
        run: yarn tsc
      - name: Runs the linter
        run: yarn lint
      - name: Runs the format checker
        run: yarn dprint check
