name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install the dependencies
        run: yarn

      - name: Run the type checker
        run: yarn tsc

      - name: Run the linter
        run: yarn lint

      - name: Run the format checker
        run: yarn dprint check
